title: Khilafah Tech
description: Critical political analysis of current and past system in the society.
show_downloads: false
google_analytics: UA-120616496-1
theme: jekyll-theme-architect
github: [metadata]